export const AUDIO_SAMPLE_RATE = 16_000;

export const SILENCE_TIMEOUT_MS = 7_000;

export const MAX_BATCH_SECONDS = 15;
export const MAX_BATCH_SAMPLES = MAX_BATCH_SECONDS * AUDIO_SAMPLE_RATE;

export const OVERLAP_SECONDS = 5;
export const OVERLAP_SAMPLES = AUDIO_SAMPLE_RATE * OVERLAP_SECONDS;
